In [1]:
import numpy as np

In [11]:
a1 = np.ones((3, 3))
# a1 = a1.reshape(3,3,1)
a2 = a1*2
a3 = a1*3
print(a1, a2, a3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] [[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]] [[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [12]:
aa = np.concatenate((a1,a2,a3), -1)
print(aa.shape, aa)

(3, 9) [[1. 1. 1. 2. 2. 2. 3. 3. 3.]
 [1. 1. 1. 2. 2. 2. 3. 3. 3.]
 [1. 1. 1. 2. 2. 2. 3. 3. 3.]]


In [15]:
tmpmtx_cplot = [[[0, 0.5, 0.5] for i in range(3)] for i in range(3)]
print(tmpmtx_cplot)

[[[0, 0.5, 0.5], [0, 0.5, 0.5], [0, 0.5, 0.5]], [[0, 0.5, 0.5], [0, 0.5, 0.5], [0, 0.5, 0.5]], [[0, 0.5, 0.5], [0, 0.5, 0.5], [0, 0.5, 0.5]]]


In [31]:
nums = []
for filename in ['a1.npy', 's124.npy']:
    i = ''
    for c in filename:
        if c.isdigit():
            # print(c)
            i += c
    print(i)

1
124
