In [1]:
import numpy as np

In [13]:
a = np.zeros((100,100))
a[:2,:] += 1
print(a[97,3])
print(a)

0.0
[[1. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [17]:
import torch
a = torch.from_numpy(np.zeros((100,3,10,10)))
b = torch.from_numpy(np.ones((100,1,10,10)))
c = torch.cat((a,b),1)
c.size()


torch.Size([100, 4, 10, 10])

In [21]:
print(c[:,-1].reshape(100,1,10,10).size())

torch.Size([100, 1, 10, 10])


In [22]:
print(len(c))

100
