In [1]:
import numpy as np

In [4]:
import torch
a = torch.ones((10,3,5,5)).cuda()
print(a[:,0].sum())

tensor(250., device='cuda:0')


In [13]:
a = np.zeros((100,100))
a[:2,:] += 1
print(a[97,3])
print(a)

0.0
[[1. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [17]:
import torch
a = torch.from_numpy(np.zeros((100,3,10,10)))
b = torch.from_numpy(np.ones((100,1,10,10)))
c = torch.cat((a,b),1)
c.size()


torch.Size([100, 4, 10, 10])

In [21]:
print(c[:,-1].reshape(100,1,10,10).size())

torch.Size([100, 1, 10, 10])


In [22]:
print(len(c))

100


In [9]:
from matplotlib import pyplot as plt
from celluloid import Camera

fig = plt.figure()
camera = Camera(fig)
for i in range(10):
    plt.plot([i] * 10)
    camera.snap()
animation = camera.animate()
animation.save('celluloid_minimal.gif', writer = 'imagemagick')

MovieWriter imagemagick unavailable; using Pillow instead.


In [1]:
import numpy as np

In [4]:
a = np.load("loss_history.npy")

In [5]:
print(a)

[10.95741367 10.20103359 10.15862465 ...  4.66714287  4.63087654
  5.13131332]


In [9]:
from learning.CoordConvModule import *
from torch import nn
import numpy as np

In [26]:
class CCenc(nn.Module):
    def __init__(self):
        super(CCenc, self).__init__()
        # Input size: [batch, 3, 100, 100]
        # Output size: [batch, 3, 100, 100]
        self.encoder = nn.Sequential(
            CoordConv(in_channels=3, out_channels=32, kernel_size = 3, stride = 1, padding = 1),
            CoordConv(in_channels=32, out_channels=32, kernel_size = 5, stride = 1, padding = 2),
            CoordConv(in_channels=32, out_channels=3, kernel_size = 3, stride = 1, padding = 1),
        )
    def forward(self, x):
        x = self.encoder(x)
        print(x.size())
        return x

In [27]:
model = CCenc()

In [28]:
a = torch.tensor(np.ones((1,3,100,100))).float()
aa = model(a)

torch.Size([1, 3, 100, 100])
